services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #BACKUP_SCHEDULE: "0 2 * * *" # Everyday at 2 am.
      BACKUP_SCHEDULE: "0 * * * *" # every hour.
    volumes:
      - ${POSTGRES_PGDATA_PATH}:/var/lib/postgresql/data
      - ./backup:/backup # Mount backup directory and script
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8082:8080"
    networks:
      - app-network

networks:
  app-network:
